### PR TITLE
Visualize child scopes

### PR DESCRIPTION
**Pull request by greeflas**
Hello!

This is fix for #402.

I'll appreciate your feedback 🙌

### CODE REVIEW

**Comment by sywhang** [comment]
Thanks @greeflas! Ideally we would add some type of visual representation to highlight the different scopes, but i think this is better than what we have for now. I'll take a look at the implementation later tonight

**Review by JacobOaks — APPROVED** [review]
I agree with @sywhang that we will probably eventually want more clear demarcation of scopes, but for now this LGTM to at the least show module's constructors at all.

**Review by r-hang — APPROVED** [review]

**Review by sywhang — APPROVED** [review]
LGTM. Thank you for the contribution!

**Comment by greeflas** [comment]
Thank you, guys, for the feedback!

**Pull request merged**
