### PR TITLE
A pick is a better tool to dig with.

### PR DESCRIPTION
**Pull request by n3wscott**
fixes: https://github.com/uber-go/dig/issues/242

### CODE REVIEW

**Comment by glibsm** [comment]
I... dig it.

🥁

**Comment by glibsm** [comment]
Why closed?

**Comment by n3wscott** [comment]
I can't sign the CLA.

**Comment by glibsm** [comment]
Oh. Can't as in it's not working or can't as in you won't?

One we should be able to easily fix, another is a totally fine stance as well :)

**Comment by n3wscott** [comment]
I am sure the button works. :(

**Comment by glibsm** [comment]
I proposed an alternative approach... #244

**Pull request closed without merging**
