### PR TITLE
Preparing release 1.7.0

### PR DESCRIPTION
**Pull request by vyshah**

### CODE REVIEW

**Comment by glibsm** [comment]
I this held up by anything else?

**Comment by abhinav** [comment]
No, this isn't held up. We just decided not to release it until after NYE.

**Comment by glibsm** [comment]
> No, this isn't held up. We just decided not to release it until after NYE.

So... to summarize... yes.
It's held up by time =]

**Comment by abhinav** [comment]
Derp, wrong release date.

**Pull request merged**
