### PR TITLE
Now with more picks in the emoji

### LINKED ISSUE #242: A hammer is a bad tool to dig with.
You should not dig with a hammer. Fix to follow.

### PR DESCRIPTION
**Pull request by glibsm**
Fixes #242

### CODE REVIEW

**Comment by n3wscott** [comment]
lololol

LGTM

**Comment by blampe** [comment]
Nice fix!

**Comment by kriskowal** [comment]
How much effort would it be to apply for SHOVEL and BUCKET or MATOCK, or AXE MATTOX emoji? Maybe EXCAVATOR? 🚜  Perhaps we should use SPOON as a stopgap? 🥄

**Comment by mh-park** [comment]
Proposal: 🥄

**Comment by robbertvanginkel** [comment]
Guess I'm not very picky with my reviews.

**Comment by glibsm** [comment]
After after some more <strike>beers</strike> significant thought taking into account all the thoughtful responses in this thread, it only stands to reason that we need to fully agree on the direction of the emoji.

For that purpose I propose we collaborate and agree on [RFC: dig emoji](https://docs.google.com/document/d/1d3T9qEZWQCj8RcHrLfyj2vCmEf-sEVoLVxsTq4Zh12E/edit?usp=sharing) prior to the merging of this pull request.

**Comment by kriskowal** [comment]
@glibsm, for the RPC, should leave a historical note: English used to more clearly separate the meanings of "dig" and "delve" based on which tool you were using. Digging was reserved for picks and mattocks, whereas delve was reserved for shovels and spades.

# ⛏  (dig)
# ♠ 🥄 (delve)

**Pull request merged**
