### PR TITLE
Add suggestions for slices and array element missing types

### PR DESCRIPTION
**Pull request by paullen**
Changes:

Added suggestions for requesting slice/array of pointers instead of the elements and vice versa

### CODE REVIEW

**Comment by paullen** [comment]
Hey. Just wanted to follow up on this PR. This seems like a good suggestion to have, it is a part of the solution for Issue #184 . Then there is the issue #389 that addresses the other half of the #184 issue.

**Comment by JacobOaks** [comment]
Hey @paullen, thanks for this PR!

I think this is a good addition, can we just add a test case similar to [this one](https://github.com/uber-go/dig/blob/a30081d72915995cb8f934ba9393256c74df9143/dig_test.go#L3251) that tests that the suggestions get properly populated from a call to `fx.Invoke`?

**Comment by paullen** [comment]
@JacobOaks Added test cases, the test coverage is now 99%, up from 98.3%. Please review. Thanks!

**Review by JacobOaks — APPROVED** [review]
Hey, sorry for the delay. LGTM!

**Review by sywhang — APPROVED** [review]
LGTM.

**Pull request merged**
