### PR TITLE
CI: test with Go 1.19 and Go 1.20

### PR DESCRIPTION
**Pull request by sywhang**
Only Go 1.19 and Go 1.20 are supported after Go 1.20 has been released.

This makes CI only run against Go 1.19 and Go 1.20.

### CODE REVIEW

**Comment by abhinav** [comment]
Need to update staticcheck

**Comment by sywhang** [comment]
huh, weird. Looks like staticcheck has a bug - it reports `scope` as not being used when it clearly is being used. 
```
internal/digtest/container.go:49:6: type scope is unused (U1000)
```

**Comment by abhinav** [comment]
Possibly "embed an alias" is enough of a corner case. 
Could probably narrow it down.

**Comment by abhinav** [comment]
This can be closed. It was superseded by #394

**Pull request closed without merging**
